import React,{useEffect,useState} from 'react';
import {IndianRupee,Users,Truck,PackageCheck,Recycle,CheckCircle2} from 'lucide-react';
import {api} from './api';

function Stat({label,value,icon:Icon}){return <div className="stat"><div className="statIcon"><Icon size={19}/></div><div><small>{label}</small><strong>{value}</strong></div></div>}

export default function AdminManagement({tab,fallbackPickups=[]}){
 const [data,setData]=useState(null),[rows,setRows]=useState(fallbackPickups),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let live=true;setLoading(true);setError('');let req=tab==='dashboard'||tab==='pickups'?Promise.all([api.adminDashboard(),api.adminPickups()]):tab==='users'?api.adminUsers():tab==='rates'?api.adminRates():tab==='reports'?Promise.all([api.adminDashboard(),api.adminRatings()]):tab==='payments'?api.adminPayments():tab==='complaints'?api.adminComplaints():Promise.resolve(null);req.then(r=>{if(!live)return;if(Array.isArray(r)){if(tab==='dashboard'||tab==='pickups'){setData(r[0]);setRows(r[1].pickups||[])}else setData({dashboard:r[0],ratings:r[1].ratings||[]})}else setData(r)}).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false}},[tab]);
 if(loading&&!data)return <div className="panel">Loading management data…</div>;
 if(error)return <div className="error">{error}</div>;
 if(tab==='rates')return <Rates rows={data?.rates||[]}/>;
 if(tab==='users')return <UsersPage users={data?.users||[]}/>;
 if(tab==='reports')return <Reports data={data}/>;
 if(tab==='payments')return <Payments rows={data?.payments||[]}/>;
 if(tab==='complaints')return <Complaints rows={data?.complaints||[]}/>;
 if(tab==='pickups')return <Pickups rows={rows}/>;
 return <Dashboard data={data} rows={rows}/>;
}
function Dashboard({data,rows}){return <><div className="stats"><Stat label="Customers" value={data?.customers??0} icon={Users}/><Stat label="Partners" value={data?.collectors??0} icon={Truck}/><Stat label="Pending pickups" value={data?.pending??0} icon={PackageCheck}/><Stat label="Revenue" value={'₹'+Math.round(data?.revenue||0)} icon={IndianRupee}/></div><div className="panel"><div className="panelHead"><div><h3>Platform pulse</h3><p>{data?.completed||0} completed · {data?.cancelled||0} cancelled · {data?.scrapKg||0} kg collected</p></div><span className="pill">{data?.openComplaints||0} open complaints</span></div>{rows.slice(0,20).map(p=><div className="listRow" key={p._id}><div><b>{p._id}</b><small>{p.status} · ₹{Math.round(p.finalAmount||p.estimatedAmount||0)}</small></div><span className="pill blue">{p.status}</span></div>)}</div></>}
function Pickups({rows}){return <div className="panel"><h3>Pickup management</h3>{rows.map(p=><div className="listRow" key={p._id}><div><b>{p._id}</b><small>{new Date(p.createdAt).toLocaleString()} · ₹{Math.round(p.finalAmount||p.estimatedAmount||0)}</small></div><span className="pill blue">{p.status}</span></div>)}</div>}
function UsersPage({users}){return <div className="panel"><div className="panelHead"><h3>Users & partners</h3><span className="pill">{users.length}</span></div>{users.map(u=><div className="listRow" key={u._id}><div><b>{u.name||'Unnamed user'}</b><small>{u.phone} · {u.role} · {u.isActive===false?'Inactive':'Active'}</small></div></div>)}</div>}
function Rates({rows}){const [saving,setSaving]=useState('');async function save(id,e){setSaving(id);try{await api.updateRate(id,Number(e.target.parentElement.querySelector('input').value));window.location.reload()}catch(x){alert(x.message)}finally{setSaving('')}}return <div className="panel"><h3>Official scrap rates</h3>{rows.map(r=><div className="rate adminRate" key={r._id}><div><b>{r.categoryId?.name||'Category'}</b><small>₹ / {r.categoryId?.unit||'kg'}</small></div><div className="rateEdit"><input defaultValue={r.rate} type="number" min="0"/><button className="primary" disabled={saving===r._id} onClick={e=>save(r._id,e)}>{saving===r._id?'Saving…':'Save'}</button></div></div>)}</div>}
function Reports({data}){const d=data?.dashboard||{},rs=data?.ratings||[];const avg=rs.length?(rs.reduce((a,x)=>a+x.rating,0)/rs.length).toFixed(1):'—';return <><div className="stats"><Stat label="Scrap collected" value={Math.round(d.scrapKg||0)+' kg'} icon={Recycle}/><Stat label="Completed" value={d.completed||0} icon={CheckCircle2}/><Stat label="Avg rating" value={avg} icon={PackageCheck}/><Stat label="Completion rate" value={d.pickups?Math.round(d.completed/d.pickups*100)+'%':'—'} icon={IndianRupee}/></div><div className="panel"><h3>Ratings</h3>{rs.map(r=><div className="listRow" key={r._id}><div><b>{r.rating}/5</b><small>{r.comment||'No comment'} · Pickup {r.pickupId}</small></div></div>)}</div></>}
function Payments({rows}){return <div className="panel"><h3>Payments & transactions</h3>{rows.map(p=><div className="listRow" key={p._id}><div><b>₹{Math.round(p.amount)}</b><small>Pickup {p.pickupId} · {p.method} · {p.status}</small></div><span className="pill">{new Date(p.createdAt).toLocaleDateString()}</span></div>)}</div>}
function Complaints({rows}){const [busy,setBusy]=useState('');async function update(id,status){setBusy(id);try{await api.updateComplaint(id,status);window.location.reload()}catch(e){alert(e.message)}finally{setBusy('')}}return <div className="panel"><h3>Complaints</h3>{rows.map(c=><div className="listRow" key={c._id}><div><b>{c.subject}</b><small>{c.description} · {c.status}</small></div><select value={c.status} disabled={busy===c._id} onChange={e=>update(c._id,e.target.value)}><option>OPEN</option><option>IN_REVIEW</option><option>RESOLVED</option><option>CLOSED</option></select></div>)}</div>}
