import React,{useEffect,useMemo,useState} from 'react';
import {io} from 'socket.io-client';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Recycle,Truck,Users,MapPin,IndianRupee,ClipboardList,Bell,Settings,Menu,ArrowRight,CheckCircle2,Clock3,PackageCheck,LogIn,RefreshCw} from 'lucide-react';
import {api} from './api';
import AdminManagement from './AdminManagement.jsx';
import './styles.css';

const fallbackRates=[['Newspaper','₹18/kg','Paper'],['Cardboard','₹12/kg','Paper'],['Iron / Steel','₹32/kg','Metal'],['Aluminium','₹145/kg','Metal'],['Plastic','₹22/kg','Plastic'],['E-waste','₹45/kg','Special']];
const demoPickups=[
 {id:'SM-1042',customer:'Ravi Kumar',area:'MVP Colony',date:'Today · 10:30 AM',items:'Newspaper, Cardboard',amount:'₹540',status:'EN_ROUTE'},
 {id:'SM-1041',customer:'Anitha Rao',area:'Seethammadhara',date:'Today · 12:00 PM',items:'Iron, Aluminium',amount:'₹1,860',status:'ACCEPTED'}
];

function App(){
 const [role,setRole]=useState('customer'),[tab,setTab]=useState('home'),[mobile,setMobile]=useState(false);
 const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('scrap_mama_user')||'null'));
 const [rates,setRates]=useState([]),[pickups,setPickups]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const nav=role==='customer'?[['home','Home',LayoutDashboard],['book','Book Pickup',Recycle],['history','History',ClipboardList],['profile','Profile',Users]]:role==='partner'?[['dashboard','Dashboard',LayoutDashboard],['requests','Requests',PackageCheck],['schedule','Schedule',Clock3],['earnings','Earnings',IndianRupee]]:[['dashboard','Dashboard',LayoutDashboard],['pickups','Pickups',Truck],['users','Users',Users],['rates','Rates',IndianRupee],['reports','Reports',ClipboardList],['payments','Payments',IndianRupee],['complaints','Complaints',Bell],['settings','Settings',Settings]];

 useEffect(()=>{let live=true;(async()=>{try{const [c,p]=await Promise.all([api.categories(),user?api.pickups():Promise.resolve({pickups:[]})]);if(live){setRates(c.categories||[]);setPickups(p.pickups||[]);}}catch(e){if(live)setError(e.message)}finally{if(live)setLoading(false)}})();return()=>{live=false}},[user]);

 async function refresh(){setLoading(true);setError('');try{const p=await api.pickups();setPickups(p.pickups||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 function loggedIn(u){setUser(u);localStorage.setItem('scrap_mama_user',JSON.stringify(u))}
 function logout(){localStorage.removeItem('scrap_mama_token');localStorage.removeItem('scrap_mama_user');setUser(null);setPickups([])}
 const requiredRole=role==='partner'?'collector':role==='admin'?'admin':'customer';
 if(!user||user.role!==requiredRole)return <Login expectedRole={requiredRole} onLogin={u=>{loggedIn(u);if(u.role==='collector')setRole('partner');if(u.role==='admin')setRole('admin')}}/>;

 return <div className="app">
  <aside className={mobile?'sidebar open':'sidebar'}>
   <div className="brand"><div className="brandMark">♻</div><div><strong>Scrap Mama</strong><span>{role==='customer'?'Customer':role==='partner'?'Partner':'Management'}</span></div></div>
   <div className="roleSwitch">{['customer','partner','admin'].map(r=><button key={r} className={role===r?'active':''} onClick={()=>{setRole(r);setTab(r==='customer'?'home':'dashboard')}}>{r}</button>)}</div>
   <nav>{nav.map(([id,label,Icon])=><button key={id} className={tab===id?'nav active':'nav'} onClick={()=>{setTab(id);setMobile(false)}}><Icon size={18}/>{label}</button>)}</nav>
   <div className="sideNote"><Recycle size={20}/><div><b>Recycle better</b><small>Doorstep pickup made simple.</small></div></div>
  </aside>
  <main className="main">
   <header><button className="menu" onClick={()=>setMobile(!mobile)}><Menu/></button><div><small>SCRAP PICKUP PLATFORM</small><h1>{title(role,tab)}</h1></div><button className="iconBtn" onClick={refresh}><RefreshCw size={19}/></button></header>
   <section className="content">{error&&<div className="error">{error}</div>}{loading&&<div className="loading">Loading live platform data…</div>}{render(role,tab,{rates:rates.length?rates:rateRows(fallbackRates),pickups,user,refresh})}</section>
  </main>
 </div>
}

function rateRows(rows){return rows.map((x,i)=>({name:x[0],rate:Number(String(x[1]).replace(/[^0-9.]/g,'')),unit:'kg',group:x[2],id:String(i)}))}
function title(role,tab){const map={home:'Good evening 👋',book:'Book a pickup',history:'Pickup history',profile:'My profile',dashboard:role==='partner'?'Partner dashboard':'Management dashboard',requests:'Pickup requests',schedule:'Pickup schedule',earnings:'Earnings',pickups:'Pickup management',users:'Users & partners',rates:'Scrap rates',reports:'Reports & analytics',settings:'Settings'};return map[tab]||'Scrap Mama'}
function render(role,tab,data){if(role==='customer')return tab==='home'?<CustomerHome {...data}/>:tab==='book'?<BookPickup {...data}/>:tab==='history'?<History {...data}/>:<Profile user={data.user}/>;if(role==='partner')return <PartnerPage tab={tab} pickups={data.pickups} refresh={data.refresh}/>;return <AdminManagement tab={tab} fallbackPickups={data.pickups}/>}

function Login({onLogin,expectedRole='customer'}){const [phone,setPhone]=useState(''),[otp,setOtp]=useState(''),[sent,setSent]=useState(false),[dev,setDev]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function send(){setBusy(true);setError('');try{const r=await api.requestOtp(phone);setSent(true);setDev(r.devOtp||'')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function verify(){setBusy(true);setError('');try{const r=await api.verifyOtp(phone,otp);localStorage.setItem('scrap_mama_token',r.token);onLogin(r.user)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="auth"><div className="authCard"><div className="brand"><div className="brandMark">♻</div><div><strong>Scrap Mama</strong><span>Doorstep scrap pickup</span></div></div><h2>Welcome back</h2><p>Login to the {expectedRole==='collector'?'Partner':expectedRole==='admin'?'Management':'Customer'} app.</p>{!sent?<><label>Mobile number</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91 98765 43210"/><button className="primary wide" disabled={busy||!phone} onClick={send}>{busy?'Sending…':'Send OTP'} <LogIn size={17}/></button></>:<><label>OTP</label><input value={otp} onChange={e=>setOtp(e.target.value)} placeholder="Enter 6-digit OTP"/>{dev&&<small className="devOtp">Development OTP: {dev}</small>}<button className="primary wide" disabled={busy||otp.length<4} onClick={verify}>{busy?'Verifying…':'Verify & continue'} <ArrowRight size={17}/></button><button className="outline wide" onClick={()=>setSent(false)}>Change number</button></>}{error&&<div className="error">{error}</div>}<small className="authNote">Production OTP delivery will be connected before launch.</small></div></div>}

function CustomerHome({rates,pickups}){
 const p=pickups[0];
 const [tracking,setTracking]=useState(null);
 if(tracking)return <Tracking pickupId={tracking} onClose={()=>setTracking(null)}/>;
 return <><div className="hero"><div><span className="eyebrow">DOORSTEP SCRAP COLLECTION</span><h2>Turn your scrap into value.</h2><p>Choose your scrap, schedule a pickup and we’ll handle the rest.</p><button className="primary">Book pickup <ArrowRight size={17}/></button></div><div className="heroArt">♻</div></div><div className="sectionHead"><h3>Today’s rates</h3><span>Updated by admin</span></div><div className="rateGrid">{rates.map(x=><div className="rate" key={x.id||x.name}><div><b>{x.name}</b><small>{x.group||x.unit}</small></div><strong>₹{x.rate}/kg</strong></div>)}</div>{p&&<><div className="sectionHead"><h3>Latest pickup</h3></div><div className="pickupCard"><div className="statusDot enroute"/><div><b>{p._id||p.id} · {p.status}</b><p>{p.scheduledTime||'Scheduled pickup'} · {p.scheduledDate?new Date(p.scheduledDate).toLocaleDateString():'Upcoming'}</p></div><button className="outline" onClick={()=>setTracking(p._id)}>Track</button></div></>}</>
}
function BookPickup({rates,refresh}){const [selected,setSelected]=useState([]),[weight,setWeight]=useState(''),[date,setDate]=useState(''),[time,setTime]=useState('10:00 AM – 12:00 PM'),[address,setAddress]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const estimate=useMemo(()=>selected.reduce((s,n)=>{const r=rates.find(x=>x.name===n);return s+Number(weight||0)*Number(r?.rate||0)},0),[selected,weight,rates]);
 async function submit(){setBusy(true);setMessage('');try{let addresses=await api.addresses();let addressId=addresses.addresses?.[0]?._id;if(!addressId){const a=await api.createAddress({label:'Home',line1:address||'Home address',city:'Visakhapatnam',state:'Andhra Pradesh'});addressId=a.address._id}await api.createPickup({addressId,items:selected.map(n=>{const r=rates.find(x=>x.name===n);return {scrapType:n,estimatedWeight:Number(weight||0),rate:Number(r?.rate||0)}}),scheduledDate:new Date(date||Date.now()),scheduledTime:time});setMessage('Pickup booked successfully.');setSelected([]);setWeight('');await refresh()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <div className="two"><div className="panel"><div className="panelHead"><div><h3>Pickup details</h3><p>Select what you want us to collect.</p></div><span className="step">1 / 3</span></div><label>Scrap categories</label><div className="chips">{rates.map(x=><button type="button" className={selected.includes(x.name)?'chip selected':'chip'} key={x.id||x.name} onClick={()=>setSelected(s=>s.includes(x.name)?s.filter(v=>v!==x.name):[...s,x.name])}>{x.name}</button>)}</div><label>Estimated quantity</label><div className="inputRow"><input value={weight} onChange={e=>setWeight(e.target.value)} placeholder="e.g. 15"/><span>kg</span></div><label>Pickup address</label><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="House / street / area"/><div className="row"><div><label>Date</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div><label>Time slot</label><select value={time} onChange={e=>setTime(e.target.value)}><option>10:00 AM – 12:00 PM</option><option>2:00 PM – 4:00 PM</option></select></div></div><button className="primary wide" disabled={busy||!selected.length||!weight} onClick={submit}>{busy?'Booking…':'Confirm pickup'} <ArrowRight size={17}/></button>{message&&<div className="success">{message}</div>}</div><div className="panel summary"><h3>Estimated value</h3><div className="estimate">₹{Math.round(estimate)}</div><p>Final amount is calculated using the actual weight recorded by the partner.</p><div className="rule"/><b>What happens next?</b><ul><li>We assign an eligible partner</li><li>Partner arrives at your address</li><li>Scrap is weighed</li><li>Final amount is confirmed</li></ul></div></div>}

function History({pickups}){const rows=pickups.length?pickups:demoPickups;return <div className="panel"><div className="panelHead"><div><h3>Pickup history</h3><p>Your pickups from the platform.</p></div></div>{rows.map(p=><div className="listRow" key={p._id||p.id}><div className="avatar">♻</div><div><b>{p._id||p.id} · {p.items?.map?.(i=>i.scrapType).join(', ')||p.items||'Scrap pickup'}</b><small>{p.scheduledTime||p.date} · {p.status}</small></div><strong>₹{Math.round(p.finalAmount||p.estimatedAmount||0)}</strong><span className="pill done">{p.status}</span></div>)}</div>}
function Profile({user}){return <div className="two"><div className="panel profile"><div className="avatar big">{(user?.name||'SM').slice(0,2).toUpperCase()}</div><h3>{user?.name||'Scrap Mama Customer'}</h3><p>{user?.phone||'Phone not set'}</p></div><div className="panel"><h3>Account</h3><p>Role: {user?.role||'customer'}</p><button className="outline" onClick={()=>{localStorage.clear();location.reload()}}>Logout</button></div></div>}
function PartnerDash({pickups}){return <><div className="stats"><Stat label="Today's pickups" value="8" icon={PackageCheck}/><Stat label="Completed" value="5" icon={CheckCircle2}/><Stat label="Pending" value="3" icon={Clock3}/><Stat label="Today's earnings" value="₹2,840" icon={IndianRupee}/></div><div className="panel"><div className="panelHead"><div><h3>Active pickup</h3><p>{pickups[0]?String(pickups[0]._id):'No active pickup'}</p></div><span className="pill blue">{pickups[0]?.status||'IDLE'}</span></div><div className="mapMock"><MapPin size={28}/><span>Navigation / live route</span></div></div></>}
function Tracking({pickupId,onClose}){
 const [pickup,setPickup]=useState(null),[location,setLocation]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{let socket;
  api.pickup(pickupId).then(r=>setPickup(r.pickup)).catch(()=>{});
  const base=(import.meta.env.VITE_API_URL||'http://localhost:4000/api').replace(/\\/api$/,'');
  socket=io(base); socket.emit('pickup:join',pickupId);
  socket.on('collector:location',data=>setLocation(data));
  socket.on('pickup:completed',()=>api.pickup(pickupId).then(r=>setPickup(r.pickup)));
  return()=>socket&&socket.disconnect();
 },[pickupId]);
 if(!pickup)return <div className="panel">Loading tracking…</div>;
 async function pay(){setBusy(true);try{const r=await api.payPickup(pickup._id,'CASH');setPickup(r.pickup)}catch(e){alert(e.message)}finally{setBusy(false)}}
 return <div className="panel"><div className="panelHead"><div><h3>Live pickup tracking</h3><p>Status: {pickup.status}</p></div><button className="outline" onClick={onClose}>Close</button></div><div className="mapMock"><MapPin size={30}/><span>{location?'Collector location received':'Waiting for collector location…'}</span></div>{pickup.status==='PAYMENT_PENDING'&&<div className="paymentBox"><h3>Final amount</h3><div className="estimate">₹{Math.round(pickup.finalAmount||0)}</div><button className="primary" disabled={busy} onClick={pay}>{busy?'Processing…':'Confirm payment (Cash)'}</button></div>}{pickup.status==='COMPLETED'&&<div className="success">Pickup completed. Final amount: ₹{Math.round(pickup.finalAmount||0)}.</div>}</div>
}
function PartnerPage({tab,pickups,refresh}){const [live,setLive]=useState([]);useEffect(()=>{api.collectorPickups().then(r=>setLive(r.pickups||[])).catch(()=>{})},[tab]);if(tab==='requests')return <PartnerRequests onRefresh={refresh}/>;if(tab==='schedule')return <PartnerSchedule pickups={live}/>;if(tab==='earnings')return <Earnings/>;return <PartnerDash pickups={live.length?live:pickups}/>}
function PartnerRequests({onRefresh}){const [rows,setRows]=useState([]),[busy,setBusy]=useState('');const load=()=>api.collectorRequests().then(r=>setRows(r.pickups||[])).catch(()=>{});useEffect(load,[]);async function accept(id){setBusy(id);try{await api.acceptPickup(id);await load();onRefresh()}catch(e){alert(e.message)}finally{setBusy('')}}return <div className="panel"><div className="panelHead"><div><h3>New pickup requests</h3><p>Accept jobs available for collection.</p></div><span className="pill">{rows.length} available</span></div>{rows.length?rows.map(p=><div className="request" key={p._id}><div><b>{p._id}</b><h4>Pickup request</h4><p>{p.scheduledTime} · {p.status}</p></div><div className="actions"><button className="primary" disabled={busy===p._id} onClick={()=>accept(p._id)}>{busy===p._id?'Accepting…':'Accept'}</button></div></div>):<div className="empty">No new requests.</div>}</div>}
function PartnerSchedule({pickups}){const [busy,setBusy]=useState('');async function advance(p){const next={ACCEPTED:'EN_ROUTE',EN_ROUTE:'ARRIVED',ARRIVED:'WEIGHING',WEIGHING:'PAYMENT_PENDING',PAYMENT_PENDING:'COMPLETED'}[p.status];if(!next)return;if(next==='PAYMENT_PENDING'){const items=(p.items||[]).map(i=>({scrapType:i.scrapType,actualWeight:Number(i.actualWeight||i.estimatedWeight||0),rate:Number(i.rate||0)}));await api.weighPickup(p._id,items)}else{await api.collectorStatus(p._id,next)}location.reload()}return <div className="panel"><h3>Active pickups</h3>{pickups.map(p=><div className="listRow" key={p._id}><div><b>{p._id}</b><small>{p.status} · Final ₹{Math.round(p.finalAmount||p.estimatedAmount||0)}</small></div><span className="pill blue">{p.status}</span>{p.status!=='COMPLETED'&&<button className="primary" onClick={()=>advance(p)}>Next</button>}</div>)}</div>}
function Requests(){return <div className="panel"><div className="panelHead"><div><h3>Pickup requests</h3><p>Nearby jobs available for acceptance.</p></div></div>{demoPickups.map(p=><div className="request" key={p.id}><div><b>{p.id}</b><h4>{p.customer}</h4><p>{p.area} · {p.items}</p><small>{p.date}</small></div><div className="actions"><b>{p.amount}</b><button className="primary">Accept</button><button className="outline">Reject</button></div></div>)}</div>}
function Schedule(){return <div className="panel"><h3>Today's schedule</h3>{demoPickups.map((p,i)=><div className="timeline" key={p.id}><div className="time">{i===0?'10:30':'12:00'}</div><div className="line"/><div><b>{p.customer}</b><p>{p.area} · {p.items}</p><span className="pill blue">{p.status}</span></div></div>)}</div>}
function Earnings(){return <div className="two"><div className="panel"><h3>This week</h3><div className="estimate">₹14,280</div><p>38 completed pickups</p><div className="bars">{[45,70,55,85,65,90,75].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></div><div className="panel"><h3>Recent earnings</h3><p>Connect collector account to show live earnings.</p></div></div>}
function Admin({tab,pickups}){if(tab==='rates')return <Rates/>;if(tab==='users')return <UsersPage/>;if(tab==='reports')return <Reports/>;if(tab==='settings')return <SettingsPage/>;return <><div className="stats"><Stat label="Customers" value="Live API" icon={Users}/><Stat label="Partners" value="API" icon={Truck}/><Stat label="Pickups loaded" value={pickups.length} icon={PackageCheck}/><Stat label="Revenue" value="API" icon={IndianRupee}/></div><div className="panel"><div className="panelHead"><div><h3>Recent pickups</h3><p>Backend-connected pickup records.</p></div></div>{pickups.map(p=><div className="listRow" key={p._id}><div><b>{p._id}</b><small>{p.status} · ₹{Math.round(p.finalAmount||p.estimatedAmount||0)}</small></div><span className="pill blue">{p.status}</span></div>)}</div></>}
function Rates(){return <div className="panel"><div className="panelHead"><div><h3>Scrap rates</h3><p>Official rates are managed through the admin API.</p></div></div>{fallbackRates.map(x=><div className="rate adminRate" key={x[0]}><div><b>{x[0]}</b><small>{x[2]} · Demo fallback</small></div><strong>{x[1]}</strong></div>)}</div>}
function UsersPage(){return <div className="panel"><h3>Users & partners</h3><p>Admin user management API is ready; live user listing is the next admin UI slice.</p></div>}
function Reports(){return <div className="stats"><Stat label="Scrap collected" value="API" icon={Recycle}/><Stat label="Completed pickups" value="API" icon={CheckCircle2}/><Stat label="Avg. pickup value" value="API" icon={IndianRupee}/><Stat label="Completion rate" value="API" icon={PackageCheck}/></div>}
function SettingsPage(){return <div className="panel"><h3>Platform settings</h3><div className="setting"><div><b>Live location sharing</b><p>Show partner location only during active pickups.</p></div><button className="toggle on"/></div><div className="setting"><div><b>Pickup notifications</b><p>Backend Socket.IO foundation is enabled.</p></div><button className="toggle on"/></div></div>}
function Stat({label,value,icon:Icon}){return <div className="stat"><div className="statIcon"><Icon size={19}/></div><div><small>{label}</small><strong>{value}</strong></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
